[project]
name = "mcwikidataparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx",
    "playwright==1.48.0",
    "pydantic",
]
